language: node_js
node_js:
    - 12
install:
    - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.55.4/hugo_0.55.4_Linux-64bit.deb
    - sudo dpkg -i hugo_0.55.4_Linux-64bit.deb
before_script:
    - npm install
script:
    - gulp build
deploy:
    provider: script
    script: 
        - gulp deploy
    skip_cleanup: true
    on:
        branch: master